<?php

/**
 * PlugintdTrack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdAudioPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PlugintdTrack extends BasetdTrack
{
  /**
   * Attempts to delete the mp3 track file before record is deleted.
   *
   * @param Doctrine_Event $event
   */
  public function preDelete($event)
  {
    $file_path = sfConfig::get('td_audio_upload_dir').'/'.$this->getFile();
    if (file_exists($file_path))
      unlink($file_path);
  }
}