<?php

/**
 * PlugintdTrackAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tdAudioPlugin
 * @subpackage model
 * @author     Tomasz Ducin <tomasz.ducin@gmail.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PlugintdTrackAlbum extends BasetdTrackAlbum
{
  /**
   * Returns short description of the video.
   *
   * @return String - short description.
   */
  public function getDescriptionShort()
  {
    return tdTools::getMbShortenedString($this->getDescription(), sfConfig::get('td_audio_short_text_sign_count'));
  }

  /**
   * Activates the track album.
   *
   * @return True
   */
  public function activate()
  {
    $this->setActive(true);
    $this->save();
    return true;
  }

  /**
   * Deactivates the track album.
   *
   * @return True
   */
  public function deactivate()
  {
    $this->setActive(false);
    $this->save();
    return true;
  }
}