td_sample_track_album:
  url:   /audio
  param: { module: tdSampleAudio, action: index }

td_sample_track_album_show:
  url:   /audio/:id
  param: { module: tdSampleAudio, action: show }

td_track_album:
  class: sfDoctrineRouteCollection
  options:
    model:                tdTrackAlbum
    module:               td_track_album
    prefix_path:          /td_track_album
    column:               id
    with_wildcard_routes: true
